### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rafis** [steelbrain/Happy-DB#8]
Doesn't work.

Under Windows, nodejs 5.1.1:

> \node_modules\happy-db\Source\Worker.js:50
> CPP.once('SupportedEvents', function(Events){
>     ^
> 
> TypeError: CPP.once is not a function
>     at Object.<anonymous> (\node_modules\happy-db\Source\Worker.js:50:5)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:313:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> (\node_modules\happy-db\Main.js:15:22)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)

Under Linux, nodejs 0.12.7:

> node_modules/redis-proto/dist/main.js:55
>     value: regeneratorRuntime.mark(function DecodeGen(Content) {
>            ^
> ReferenceError: regeneratorRuntime is not defined
>     at node_modules/happy-db/node_modules/redis-proto/dist/main.js:55:12
>     at Object.<anonymous> (node_modules/happy-db/node_modules/redis-proto/dist/main.js:129:3)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (node_modules/happy-db/node_modules/redis-proto/main.js:7:20)
>     at Module._compile (module.js:460:26)

**Comment by steelbrain** [comment]
It used to work, haven't touched in a long-time. Can you describe what your use case looks like? If it's a solid one, I can re-work on it

**Comment by steelbrain** [comment]
Closing due to lack of response
